module.exports = {
  exportPathMap: function () {
    return {
      "/": { page: "/" },
      "/join": { page: "/join" },
      "/our-developers": { page: "/our-developers" },
      "/unleash": { page: "/unleash" },
      "/blog": { page: "/blog" },
      "/portfolio": { page: "/portfolio" },
      "/hire-developers": { page: "/hire-developers" },
      "/hire-android-developers": { page: "/hire", query: { title: "android" } },
      "/hire-angular-developers": { page: "/hire", query: { title: "angular" } },
      "/hire-backend-developers": { page: "/hire", query: { title: "backend" } },
      "/hire-django-developers": { page: "/hire", query: { title: "django" } },
      "/hire-drupal-developers": { page: "/hire", query: { title: "drupal" } },
      "/hire-flask-developers": { page: "/hire", query: { title: "flask" } },
      "/hire-front-developers": { page: "/hire", query: { title: "front" } },
      "/hire-go-developers": { page: "/hire", query: { title: "go" } },
      "/hire-ionic-developers": { page: "/hire", query: { title: "ionic" } },
      "/hire-ios-developers": { page: "/hire", query: { title: "ios" } },
      "/hire-java-developers": { page: "/hire", query: { title: "java" } },
      "/hire-javascript-developers": { page: "/hire", query: { title: "javascript" } },
      "/hire-laravel-developers": { page: "/hire", query: { title: "laravel" } },
      "/hire-mobile-developers": { page: "/hire", query: { title: "mobile" } },
      "/hire-node-developers": { page: "/hire", query: { title: "node" } },
      "/hire-php-developers": { page: "/hire", query: { title: "php" } },
      "/hire-python-developers": { page: "/hire", query: { title: "python" } },
      "/hire-react-developers": { page: "/hire", query: { title: "react" } },
      "/hire-redux-developers": { page: "/hire", query: { title: "redux" } },
      "/hire-ruby-developers": { page: "/hire", query: { title: "ruby" } },
      "/hire-symfony-developers": { page: "/hire", query: { title: "symfony" } },
      "/hire-wordpress-developers": { page: "/hire", query: { title: "wordpress" } },
    }
  },
}
